name: writing_writer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ## own pack ##
  blur_glass: ^0.0.1
  click_text_field: ^0.0.5
  ## own pack ##
  # 系统/文件路径
  path_provider: ^2.0.12
  url_launcher: ^6.1.8
  # 状态管理
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  # 全局单例模式
  get_it: ^7.2.0
  # 事件总线
  event_bus: ^2.0.0
  # 动画
  lottie: ^2.2.0
  # String扫描匹配
  string_scanner: ^1.1.1
  # map对象运算比较
  collection: ^1.17.0
  # 下拉选项框组件
  dropdown_button2: ^1.9.2
  # websockets
  web_socket_channel: ^2.3.0
  # webdav
  webdav_client: ^1.2.0

  ## pc pack use ##
  circular_menu: ^2.0.1
  ## pc pack use ##

  ## mobile pack use ##
  animated_stack: ^0.2.0
  ## mobile pack use ##

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/anim/