name: writing_writer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ## own pack
  blur_glass: ^0.0.1
  click_text_field: ^0.0.5
  ## own pack
  path_provider: ^2.0.11
  url_launcher: ^6.1.6
  # 状态管理
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  # 不同设备屏幕
  responsive_builder: ^0.4.3
  # 动画
  lottie: ^2.0.0
  # api
  string_scanner: ^1.1.1
  # tool
  collection: ^1.17.0
  # 事件总线
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/anim/